### ISSUE TITLE
Merge the different OrganizeTrialInfo

### ISSUE THREAD

**Issue by pinheirochagas** [pinheirochagas/lbcn_preproc#1]
Ying could you please merge the OrganizeTrialInfoMemoria & OrganizeTrialInfoMemoria_GS_Veb and also OrganizeTrialInfoMMR & OrganizeTrialInfoMMR_rest? Thanks!

**Comment by fangyingr** [comment]
Hi Pedro, I think we can use the OrganizeTrialInfoMemoria_GS_Veb to replace the old one. I just added a new column to separate the general and specific veb in memory condition.
