### ISSUE TITLE
Create folders

### ISSUE THREAD

**Issue by pinheirochagas** [pinheirochagas/lbcn_preproc#10]
Let's have:

Band - create folders
   HFB/Epoched - wavelet filer
Spec - create folders
  Dense/Epoched - wavelet filer

**Comment by fangyingr** [comment]
Oh I thought the file hierarchy would be:  
BandData
   - HFB (- create folders)-Epoch
   - theta(- create folders) -Epoch
   -alpha ( - create folders) -Epoch
....
SpecData
   - Dense(- create folders) -Epoch
   - Spec (- create folders)-Epoch
....

Let me know if I'm wrong :)))
@pinheirochagas @adaitch

**Comment by pinheirochagas** [comment]
We might remove the create folder for specific bands from the wavelet filter to an additional dedicated create folder function.
