### ISSUE TITLE
Merge the OrganizeTrialInfo

### ISSUE THREAD

**Issue by pinheirochagas** [pinheirochagas/lbcn_preproc#2]
Ying could you please merge the OrganizeTrialInfoMemoria & OrganizeTrialInfoMemoria_GS_Veb and also OrganizeTrialInfoMMR & OrganizeTrialInfoMMR_rest? Thanks!

**Comment by fangyingr** [comment]
Hi Pedro, I feel like we can change the name (the OrganizeTrialInfoMemoria_GS_Veb) into OrganizeTrialInfoMemoria and replace the old one. Cause I just added an additional column at the end of trialinfo to separate the general and specific veb. For the MMR I'll send you as soon as I fix it.

**Comment by pinheirochagas** [comment]
OK, closing the issue.
