### ISSUE TITLE
dealing with empty categories in PlotTrialAvgAll and PlotERSPAll

### ISSUE THREAD

**Issue by adaitch** [pinheirochagas/lbcn_preproc#6]
GradCPT will have some empty categories for some columns, so can we replace this:

    if nargin < 9 || isempty(conds)
        conds = categories(data_all.trialinfo.(column));
    end    

with:

    if nargin < 9 || isempty(conds)
        tmp = find(~cellfun(@isempty(data_all.trialinfo.(column)))
        conds = unique(data_all.trialinfo.(column)(tmp));
    end

**Comment by pinheirochagas** [comment]
Done, thanks!
